DROP TABLE PEDIDO CASCADE CONSTRAINT;

CREATE TABLE PEDIDO
(
NUMERO          NUMBER(6),
DATA            DATE          NOT NULL,
PRAZO_ENTREGA   DATE          NULL,
RUA             VARCHAR2(80)  NULL,
NR              NUMBER(4)     NULL,  
BAIRRO          VARCHAR2(50)  NULL,
COMPLEMENTO     VARCHAR2(100) NULL,
CIDADE          VARCHAR2(50)  NULL,
UF              VARCHAR2(2)   NULL,
CEP             VARCHAR2(10)  NULL,
TOTAL_FATURA    NUMBER(8,2)   NULL,
CODIGO_CLI      NUMBER        NOT NULL,
MATRICULA_VEN   NUMBER        NOT NULL
)
;

ALTER TABLE PEDIDO
ADD CONSTRAINT PK_PEDIDO PRIMARY KEY(NUMERO)
;

ALTER TABLE PEDIDO
ADD CONSTRAINT FK_PED_CLIENTE FOREIGN KEY(CODIGO_CLI) REFERENCES CLIENTE(CODIGO)
ADD CONSTRAINT FK_PED_VENDEDOR FOREIGN KEY(MATRICULA_VEN) REFERENCES VENDEDOR(MATRICULA)
;


DROP TABLE ESTOQUE CASCADE CONSTRAINT;

CREATE TABLE ESTOQUE
(
DATA_ENTRADA    DATE,
CODIGO_PRO      INTEGER     NOT NULL,
CODIGO_PRA      NUMBER(3)   NOT NULL,
QUANTIDADE      NUMBER(5)   NOT NULL,
DATA_VALIDADE   DATE        NULL
)
;

ALTER TABLE ESTOQUE
ADD CONSTRAINT PK_ESTOQUE PRIMARY KEY (DATA_ENTRADA,CODIGO_PRO,CODIGO_PRA)
;

DROP TABLE CAPACIDADE_ESTOQUE CASCADE CONSTRAINT;

CREATE TABLE CAPACIDADE_ESTOQUE
(
CODIGO_PRO      INTEGER,
CODIGO_PRA      NUMBER(3),
QUANTIDADE      NUMBER(5)   NOT NULL
)
;

ALTER TABLE CAPACIDADE_ESTOQUE
ADD CONSTRAINT PK_CAPACIDADE_ESTOQUE PRIMARY KEY (CODIGO_PRO,CODIGO_PRA)
;

ALTER TABLE CAPACIDADE_ESTOQUE
ADD CONSTRAINT FK_CAP_EST_PRATELEIRA FOREIGN KEY (CODIGO_PRA) REFERENCES PRATELEIRA (CODIGO)
ADD CONSTRAINT FK_CAP_EST_PRODUTO FOREIGN KEY (CODIGO_PRO) REFERENCES PRODUTO (CODIGO)
;

DROP TABLE ITEM_PRODUTO CASCADE CONSTRAINT;

CREATE TABLE ITEM_PRODUTO
(
CODIGO_PRO      INTEGER     NOT NULL,
NUMERO_PED      NUMBER(6)   NOT NULL,
QUANTIDADE      NUMBER(5)   NOT NULL,
PRECO_UNITARIO  NUMBER(5,2) NOT NULL,
VALOR_ITEM      NUMBER(7,2) NULL
)
;

ALTER TABLE ITEM_PRODUTO
ADD CONSTRAINT PK_ITEM_PRODUTO PRIMARY KEY (CODIGO_PRO, NUMERO_PED)
;

ALTER TABLE ITEM_PRODUTO
ADD CONSTRAINT FK_ITEM_PRODUTO FOREIGN KEY (CODIGO_PRO) REFERENCES PRODUTO (CODIGO)
ADD CONSTRAINT FK_ITEM_PEDIDO FOREIGN KEY (NUMERO_PED) REFERENCES PEDIDO (NUMERO)
;






