--1) Juntar as tabelas FONE_CLIENTE e FONE_VENDEDOR em uma única tabela,
--relacionando-a com CLIENTE e VENDEDOR. Criar as regras de integridade básica
--necessárias para garantir a qualidade dos dados. A nova tabela se chamará FONE,
--com ascolunas CODIGO_CLI, MATRICULA_VEN, NUMERO. Quando a coluna
--CODIGO_CLI estiver preenchida a MATRICULA_VEN estará vazia e vice-versa.

CREATE TABLE FONE (CODIGO_CLI NUMBER NULL, MATRICULA_VEN NUMBER NULL, NUMERO VARCHAR2(20) NOT NULL,
CONSTRAINT PK_FONE PRIMARY KEY (CODIGO_CLI, MATRICULA_VEN, NUMERO),
CONSTRAINT FK_FONE_CLI FOREIGN KEY (CODIGO_CLI)
REFERENCES CLIENTE (CODIGO),
CONSTRAINT FK_FONE_VEN FOREIGN KEY (MATRICULA_VEN)
REFERENCES VENDEDOR (MATRICULA),
CONSTRAINT CHK_FONE_XOR CHECK (
(CODIGO_CLI     IS NOT NULL AND MATRICULA_VEN IS NULL) OR
(CODIGO_CLI IS NULL AND MATRICULA_VEN IS NOT NULL))
);

SELECT *
FROM FONE;
